### PR TITLE
[LIME-26] Updating poms with proper dependency versions and exclusions.

### PR DESCRIPTION
**Pull request by heuermh**
Work in progress.

I've been whittling down dependencies to the minimum that will pass unit tests, haven't tested on the cluster yet.

Will also need a release profile, though perhaps that should be in a separate pull request with release scripts.

### CODE REVIEW

**Comment by heuermh** [comment]
Rebased.

**Comment by devin-petersohn** [comment]
@heuermh Is this still WIP?

**Comment by heuermh** [comment]
> @heuermh Is this still WIP?

If you can test #33, which includes the commit from this PR, on the bdg cluster, then both should be ready to merge.  I don't have access today, and am worried some runtime classpath issues might show up in cluster mode that don't show up for me locally.

**Comment by devin-petersohn** [comment]
Ok! No problem. I will try that.

**Comment by devin-petersohn** [comment]
Thanks @heuermh.

**Pull request merged**
